# XDG Desktop Portal
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland

# QT
env = QT_QPA_PLATFORM,wayland;xcb
env = QT_QPA_PLATFORMTHEME,qt6ct
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1
env = QT_SCALE_FACTOR,1.25

# GTK
env = GDK_SCALE,1.25

# Mozilla
env = MOZ_ENABLE_WAYLAND,1

# Cursor size
env = XCURSOR_SIZE,32

# AppImage
env = APPIMAGELAUNCHER_DISABLE,1

# OZONE
env = OZONE_PLATFORM,wayland

