# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

windowrulev2 = float, class:.*

windowrulev2 = size 1200 900, class:.*
windowrulev2 = size 1600 1200, class:^(firefox|Firefox)$

windowrulev2 = center, class:.*
