# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

windowrulev2 = opacity 1.0 override, title: (.*Фільм.*)
windowrulev2 = opacity 1.0 override, title: (.*фільм.*)
windowrulev2 = opacity 1.0 override, title: (.*дивитися.*)

windowrulev2 = opacity 1.0 override, title: (.*Фильм.*)
windowrulev2 = opacity 1.0 override, title: (.*смотреть.*)
windowrulev2 = opacity 1.0 override, title: (.*Смотреть.*)

windowrulev2 = opacity 1.0 override, title: (.*HBO.*)

windowrulev2 = opacity 1.0 override, title: (.*Prime Video.*)

windowrulev2 = opacity 1.0 override, title: (.*Netflix.*)

windowrulev2 = opacity 1.0 override, title: (.*Disney.*)

windowrulev2 = opacity 1.0 override, title: (.*Twitch.*)

windowrulev2 = opacity 1.0 override, title: (.*Kick.*)

windowrulev2 = opacity 1.0 override, title: (.*Libre.*)
windowrulev2 = opacity 1.0 override, title: ^Picture-in-Picture$
